[credentials]
usernames.sample_user.name = "sample_user"
usernames.sample_user.email = "sample@email.com"
usernames.sample_user.password = "$2b$12$NsNIvSxA9ofB7FvtC1X0YOTYFpQcl2JkSjqp2d.04PCvMm2QdvuFq"

[cookie]
expiry_days = 1
key = "some_signature_key"
name = "some_cookie_name"
