[credentials]
  [credentials.usernames.sample_user]
    name = "sample_user"
    email = "sample@email.com"
    password = "$2b$12$6eY3MYu0xsqPgW.EuLuGJu2zeKsxOye3jgDF2Jho5NWoN63RY14Ni"

[cookie]
expiry_days = 1
key = "some_signature_key"
name = "some_cookie_name"
